
[package]
name = "hex-net-io"
version = "0.1.0"
edition = "2024"

[lib]
doctest = false

[dependencies]
hex-net-core = { workspace = true }


[target.'cfg(target_os = "linux")'.dependencies]
libc = "0.2.189"

[dev-dependencies]
hex-net-sim = { workspace = true }

[[bench]]
name = "pps"
harness = false
